./noscl relay remove wss://satstacker.cloud
./noscl relay remove wss://nostr-relay.wlvs.space
./noscl relay remove wss://nostr.semisol.dev
./noscl relay remove wss://nostr-pub.semisol.dev
./noscl relay remove wss://nostr-verified.wellorder.net
./noscl relay remove wss://nostr.bitcoiner.social
./noscl relay remove wss://nostr.openchain.fr
./noscl relay remove wss://nostr.delo.software
./noscl relay remove wss://relay.nostr.info
./noscl relay remove wss://relay.nostr.pro
./noscl relay remove wss://relay.damus.io
./noscl relay remove wss://nostr.zaprite.io
./noscl relay remove wss://nostr.oxtr.dev
./noscl relay remove wss://nostr.ono.re
./noscl relay remove wss://nostr-pub.wellorder.net
./noscl relay remove wss://relay.oldcity-bitcoiners.info
./noscl relay remove wss://nostr.rdfriedl.com
./noscl relay remove wss://relay.farscapian.com
./noscl relay remove wss://relay.sovereign-stack.org
./noscl relay remove wss://nostr-2.zebedee.cloud
./noscl relay remove wss://nostr.shadownode.org
./noscl relay remove wss://relay.r3d.red
./noscl relay remove wss://nostr.fmt.wiz.biz
./noscl relay remove wss://relay.cryptocculture.com
./noscl relay remove wss://nostr.fly.dev
./noscl relay remove wss://nostr.nordlysln.net
./noscl relay remove wss://nostr.zerofeerouting.com
./noscl relay remove wss://no.str.cr
./noscl relay remove wss://relay.nostr.ch
./noscl relay remove wss://public.nostr.swissrouting.com
./noscl relay remove wss://nostr-relay.nonce.academy
./noscl relay remove wss://nostr.rewardsbunny.com
./noscl relay remove wss://nostr.slothy.win
./noscl relay remove wss://nostr.coinos.io
./noscl relay remove wss://relay.nostropolis.xyz/websocket
./noscl relay remove wss://lv01.tater.ninja
./noscl relay remove wss://nostr.orba.ca
./noscl relay remove wss://nostr.supremestack.xyz
./noscl relay remove wss://nostrrelay.com
./noscl relay remove wss://nostr-01.bolt.observer
./noscl relay remove wss://nostr.mom
./noscl relay remove wss://relay.nostr.au
./noscl relay remove wss://nostr.oooxxx.ml
./noscl relay remove wss://nostr.yael.at
./noscl relay remove wss://nostr-relay.trustbtc.org
./noscl relay remove wss://nostr.8e23.net
./noscl relay remove wss://nostr.actn.io
./noscl relay remove wss://relay.sendstr.com
./noscl relay remove wss://nostr.satsophone.tk
./noscl relay remove wss://nostr-relay.derekross.me
./noscl relay remove wss://nostr.jiashanlu.synology.me
./noscl relay remove wss://nostr.radixrat.com
./noscl relay remove wss://nostr.shawnyeager.net
./noscl relay remove wss://nostr-dev.wellorder.net
./noscl relay remove wss://nostr.mwmdev.com
./noscl relay remove wss://relay.21spirits.io
./noscl relay remove wss://nostr-relay.freedomnode.com
./noscl relay remove wss://wlvs.space
./noscl relay remove wss://nostr.einundzwanzig.space
./noscl relay remove wss://nostr.d11n.net
./noscl relay remove wss://nostr1.tunnelsats.com
./noscl relay remove wss://nostr.leximaster.com
./noscl relay remove wss://nostr.hugo.md
./noscl relay remove wss://mule.platanito.org
./noscl relay remove wss://relay.ryzizub.com
./noscl relay remove wss://nostr.w3ird.tech
./noscl relay remove wss://nostr.robotechy.com
./noscl relay remove wss://relay.stoner.com
./noscl relay remove wss://relay.nostrmoto.xyz
./noscl relay remove wss://relay.boring.surf
./noscl relay remove wss://nostr.bongbong.com
./noscl relay remove wss://nostr.mado.io
./noscl relay remove wss://nostr.corebreach.com
./noscl relay remove wss://nostr.hyperlingo.com
./noscl relay remove wss://nostr.ethtozero.fr
./noscl relay remove wss://nostr-relay.digitalmob.ro
./noscl relay remove wss://jiggytom.ddns.net
./noscl relay remove wss://nostr.sectiontwo.org
./noscl relay remove wss://nostr.roundrockbitcoiners.com
./noscl relay remove wss://nostr.nodeofsven.com
./noscl relay remove wss://nostr.jimc.me
./noscl relay remove wss://nostr.utxo.lol
./noscl relay remove wss://relay.lexingtonbitcoin.org
./noscl relay remove wss://nostr.mikedilger.com
./noscl relay remove wss://relay.nyx.ma
./noscl relay remove wss://nostr.shmueli.org
./noscl relay remove wss://wizards.wormrobot.org
./noscl relay remove wss://nostr.orangepill.dev
./noscl relay remove wss://paid.no.str.cr
./noscl relay remove wss://nostr.sovbit.com
./noscl relay remove wss://relay.nostrid.com
./noscl relay remove wss://nostr1.starbackr.me
./noscl relay remove wss://nostr-relay.schnitzel.world
./noscl relay remove wss://sg.qemura.xyz
./noscl relay remove wss://nostr.xpersona.net
./noscl relay remove wss://relay.n057r.club
./noscl relay remove wss://nostr.digitalreformation.info
./noscl relay remove wss://nostr.gromeul.eu
./noscl relay remove wss://nostr2.actn.io
./noscl relay remove wss://nostr-relay.usebitcoin.space
./noscl relay remove wss://nostrich.friendship.tw
./noscl relay remove wss://nostr.mustardnodes.com
./noscl relay remove wss://nostr.bch.ninja
./noscl relay remove wss://nostr-relay.j3s7m4n.com
./noscl relay remove wss://nostr.demovement.net
./noscl relay remove wss://nostr.thesimplekid.com
./noscl relay remove wss://nostr.blocs.fr
./noscl relay remove wss://no.str.watch
./noscl relay remove wss://nostr.vulpem.com
./noscl relay remove wss://nostr.hackerman.pro
./noscl relay remove wss://nostr3.actn.io
./noscl relay remove wss://nostr.pwnshop.cloud
./noscl relay remove wss://nostr.mrbits.it
./noscl relay remove wss://nostr.massmux.com
